### ISSUE TITLE
self.bone.bbone_easein error

### ISSUE THREAD

**Issue by kosirm** [gnastacast/bendy_bone_handles#3]
I really like this script, thank you so much for sharing.
In blender 2.82 I got this error...
![bone-handles](https://user-images.githubusercontent.com/54502/74678391-246bcc00-51bb-11ea-91cc-ec78093ff0fd.PNG)
Othervise script is working really fine.

**Comment by gnastacast** [comment]
You can click "Allow execution" and it should be fine. That warning is to prevent scripts you don't trust from changing things on your computer. In this case it's a small driver script, so nothing to worry about.
